### ISSUE TITLE
Pfizer/Moderna Split is far from CDC actuals

### ISSUE THREAD

**Issue by pedrohforli** [youyanggu/covid19-cdc-vaccination-data#1]
In the adjusted csv provided, although the absolute numbers look correct one of the most interesting pieces of the data, the splits between vaccines, is far from the reported numbers from CDC.

As of 2021-02-03, the CDC reports 18M administered Pfizer doses and 15M Moderna doses. The dataset provided, on the other hand, shows 30M Pfizer and 3M Moderna for the same date, and it looks like this difference is being driven by 0 daily Moderna doses for the past few weeks in most states (so I assume that the likely source of this information is no longer reporting it)

**Comment by youyanggu** [comment]
Can you point out which row and column you are referring to? I took a look at the adjusted csv and I see 18M Pfizer and 15M Moderna for the US. I cannot find the 30M/3M that you are referring to.

**Comment by pedrohforli** [comment]
As pointed out I tested with the data provided on 2021-02-04, which I don't have anymore, but with the data from yesterday here's a snapshot of what I'm running:
![image](https://user-images.githubusercontent.com/10605142/107124557-5d48f900-6883-11eb-990e-469ca3b9d100.png)

You are looking at the US total, which is correct, but I'm more interested in the state by state info.
![image](https://user-images.githubusercontent.com/10605142/107124655-f7a93c80-6883-11eb-963f-72d2543a310b.png)

**Comment by youyanggu** [comment]
I see what you're talking about now - thanks!

It seems like the CDC stopped releasing state-by-state breakdowns of Pfizer vs Moderna starting on Jan 14, so I went ahead and removed the interpolations from Jan 14 onwards for states and LTC. Only the US location should have complete "administered_pfizer" and "administered_moderna" rows.

Thanks again for bringing this to my attention.
