### ISSUE TITLE
Jansen vaccination

### ISSUE THREAD

**Issue by lucasrodes** [youyanggu/covid19-cdc-vaccination-data#3]
Hi, 
Thanks for your work. I am using your data in my project
https://github.com/sociepy/covid19-vaccination-subnational, so I really appreciate your work!

I noticed that the USA started vaccinating with Jansen uni-dose (reported in https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_data). Do you plan on add this to your dataset?

Thanks!

**Comment by youyanggu** [comment]
I'm glad you found this repo helpful. Unfortunately, I am actually no longer updating as of March 8. See my blog post here: https://youyanggu.com/blog/one-year-later
